language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
env:
  global:
    - TRUNK_BRANCH="master"
before_script:
  - npm install -g npm@latest
install:
  - npm ci
  - source ./.travis/create-dotenv.sh
script: skip
jobs:
  include:
    - stage: test
      script:
        - npm test -- -u --detectOpenHandles --forceExit
    - stage: deploy
      if: branch = env(TRUNK_BRANCH) AND type = push
      node_js: lts/*
      script:
        - npm install -g expo-cli
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
    - stage: release
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - source ./.travis/prepare-release.sh || travis_terminate 1
        - npm run release || travis_terminate 1
        - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
