import {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_AUTH_MAIL,
  FIREBASE_AUTH_PASS,
  PUSH_ENDPOINT,
  PUSH_SECRET_CODE,
  PUSH_APP_NAME
} from "react-native-dotenv";

const buildEnv = process.env;
const { env: runtimeEnv } = global.process || {};

export default {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_AUTH_MAIL,
  FIREBASE_AUTH_PASS,
  PUSH_ENDPOINT,
  PUSH_SECRET_CODE,
  PUSH_APP_NAME,
  ...buildEnv,
  ...runtimeEnv
};
